In [4]:
import pandas as pd

dados_elenco = {
    "Jogador": ["Neymar", "Arthur", "Coutinho", "Brasao", "Luan Peres"],
    "Posicao": ["Atacante", "Meia Armador", "Meia Atacante", "Goleiro", "Zagueiro"],
    "Jogos": [100, 15, 6, 130, 101],
    "Assistencias": [10, 5, 5, 1, 3]
}

tabela_santos = pd.DataFrame(dados_elenco)
tabela_santos

      Jogador        Posicao  Jogos  Assistencias
0      Neymar       Atacante    100            10
1      Arthur   Meia Armador     15             5
2    Coutinho  Meia Atacante      6             5
3      Brasao        Goleiro    130             1
4  Luan Peres       Zagueiro    101             3

In [ ]:
# Para selecionar apenas as colunas que nos interessam em um DataFrame, passamos uma lista com os nomes dessas colunas dentro de colchetes duplos [[ ]]:

# Seleciona apenas os nomes e as assistências
colunas_foco = tabela_santos[["Jogador", "Assistencias"]]

# -----------------------------------------------------------------------------------

# Para criar um ranking e ordenar os atletas, usamos o método .sort_values():

# Por padrão, ele ordena do menor para o maior (crescente).

# No futebol, quase sempre queremos o ranking do maior para o menor (decrescente). Para isso, ativamos o parâmetro ascending=False:

# Ordena do maior para o menor número de jogos
ranking_jogos = tabela_santos.sort_values(by="Jogos", ascending=False)
ranking_jogos

      Jogador        Posicao  Jogos  Assistencias
3      Brasao        Goleiro    130             1
4  Luan Peres       Zagueiro    101             3
0      Neymar       Atacante    100            10
1      Arthur   Meia Armador     15             5
2    Coutinho  Meia Atacante      6             5

In [12]:
tabela_ofensiva = tabela_santos[["Jogador", "Posicao", "Assistencias"]]
ranking_assistencias = tabela_ofensiva.sort_values(by="Assistencias", ascending=False)

ranking_assistencias

      Jogador        Posicao  Assistencias
0      Neymar       Atacante            10
1      Arthur   Meia Armador             5
2    Coutinho  Meia Atacante             5
4  Luan Peres       Zagueiro             3
3      Brasao        Goleiro             1