Seja muito bem-vindo à Semana 2 - Dia 5: Agrupamentos e métricas por equipe (groupby, agg)! ⚽📊

No futebol, nem sempre analisamos atletas de forma isolada. Muitas vezes a diretoria ou a comissão técnica quer enxergar o panorama coletivo: "Qual time do campeonato tem a maior média de finalizações?", "Qual equipe comete mais faltas no torneio?" ou "Qual é o total de desarmes por setor do campo?".

Para responder a perguntas coletivas a partir de dados individuais, usamos o agrupamento com o método .groupby() do Pandas.

Pense no groupby como a divisão dos atletas nos vestiários antes da partida.

Dividir (Split): O Pandas separa as linhas da tabela em grupos com base nos valores de uma coluna (por exemplo, agrupar todos os jogadores do "Santos", todos do "Flamengo", etc.).

Aplicar (Apply): Ele aplica um cálculo matemático a cada grupo (como somar os gols ou tirar a média de idade).

Combinar (Combine): Ele junta os resultados em uma nova tabela consolidada.

In [ ]:
import pandas as pd

dados = {
    "jogador": ["Atleta 1", "Atleta 2", "Atleta 3", "Atleta 4"],
    "time": ["Santos", "Santos", "Palmeiras", "Palmeiras"],
    "gols": [10, 5, 8, 12]
}

df = pd.DataFrame(dados)

# 1. Agrupamento simples com soma:
# Queremos agrupar por 'time' e somar os 'gols' de cada um
gols_por_time = df.groupby("time")["gols"].sum().reset_index()
display(gols_por_time)

# Dica tática: Usamos .reset_index() ao final para que a coluna "time" 
# continue sendo uma coluna comum da tabela, facilitando futuras visualizações e ordenações.

        time  gols
0  Palmeiras    20
1     Santos    15

In [2]:
# Se você quiser calcular mais de uma métrica ao mesmo 
# tempo (como a soma total e a média), usamos o método .agg():

# Média e soma de gols por time
resumo_times = df.groupby("time")["gols"].agg(["sum", "mean"]).reset_index()
display(resumo_times)

        time  sum  mean
0  Palmeiras   20  10.0
1     Santos   15   7.5

In [18]:
import pandas as pd

dados_jogadores = {
    "jogador": ["Atleta 1", "Atleta 2", "Atleta 3", "Atleta 4", "Atleta 5", "Atleta 6"],
    "time": ["Santos", "Santos", "Palmeiras", "Palmeiras", "Corinthians", "Corinthians"],
    "gols_por_time": [10, 5, 8, 12, 7, 9],
    "desarmes": [15, 20, 10, 25, 30, 18]
}

df_campeonato = pd.DataFrame(dados_jogadores)

resumo_equipes = df_campeonato.groupby("time")["gols_por_time"].agg(["sum", "mean"]).round(2).reset_index()
resumo_equipes.rename(columns={"sum": "total_gols", "mean": "media_gols"}, inplace=True)
resumo_equipes = resumo_equipes.sort_values(by="media_gols", ascending=False).reset_index(drop=True)
display(resumo_equipes)

          time  total_gols  media_gols
0    Palmeiras          20        10.0
1  Corinthians          16         8.0
2       Santos          15         7.5